trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'
    platform: '$(platform)'
    configuration: '$(configuration)'
    clean: true
    createLogFile: true
