trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '16.0'
    platform: $(platform)
    configuration: $(configuration)
    clean: true
    createLogFile: true
