trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '15.0'
    platform: '$(platform)'
    configuration: '$(configuration)'
    clean: true
    createLogFile: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).7z'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nt-native-debug'
    publishLocation: 'Container'
    